name: "Deploiement du site"

on:
  push:
    branches:
      - main

jobs:
    deploy:
        name: Build & Deploy
        runs-on:  ubuntu-latest

        steps:
            - name: Récupération du code
              uses: actions/checkout@v4
            - name: Installation de nodejs
              uses: actions/setup-node@v4
              with:
                node-version: "20.18.0"
            - name: Installation des deps npms
              run: npm ci
            - name: "Lance le build"
              run: npm run build
            - name: "Livrer le code en ssh"
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                port: ${{ secrets.PORT }}
                key: ${{secrets.KEY}}
                source: "*, !node_modules,!.vscode"
                target: /var/www/app
            - name: "Lancement du projet"
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                port: ${{ secrets.PORT }}
                key: ${{secrets.KEY}}
                script: |
                  cd /var/www/app
                  npm ci
